In [1]:
# 1. numpy创建数组

import numpy as np
# 1.1 采用列表方式创建
a0 = np.array([1,2,3,4])
# 1.2 采用元组方式创建
a1 = np.array((1,2,3,4))

print(a0, a1)

[1 2 3 4] [1 2 3 4]


In [4]:
# 2. 创建多维数组
a = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


In [5]:
# 3. 生成随机数组 
#   3.1 .arange()
#   第一个值表示开始值，第二个值表示终值，第三个值表示步长
#   生成的值中不包括终值
a = np.arange(0,1,0.1)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
#  3.2 .linspace()
# 前两个参数和arange一样，第三个值表示元素的个数
#  生成的值包括终值，如果要不包含终值，只需加 endpoint = False 即可
a = np.linspace(0,10, 8, endpoint=False)
print(a)

[0.   1.25 2.5  3.75 5.   6.25 7.5  8.75]


In [27]:
# 4. 创建一个随机数组的函数： 
#   rand 产生0到1间的随机数
#   randn 产生符合正标准态分布的随机数
#   randint 产生指定区间的随机数
#   normal 产生符合正态分布的随机数
#   uniform 产生符合均匀分布的随机数
#   seed 产生随机种子数
#   choice 从指定样本中随机选择数据
#   shuffle 将指定样本的元素顺序打乱

a = np.random.rand(2,2)
b = np.random.randn(3, 3)
c = np.random.randint(0,9, (3,2))

print(a)
print('----')
print(b)
print('----')
print(c)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
----
[[-0.52817175 -1.07296862  0.86540763]
 [-2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794]]
----
[[7 0]
 [6 7]
 [6 1]]


In [29]:
# np.zeros() 生成元素全是0为占位
# np.ones() 生成元素全是1为占位
# np.zeros_like(a) 生成形状和a一样且元素全是0为占位的数组
# np.ones_like(a) 生成形状和a一样且元素全是1为占位的数组

zerosArr = np.zeros([3,3])
print(zerosArr)
onesArr = np.ones([2,2])
print(onesArr)
a = np.array([[1,2,3,4],[4,5,6,7],[3,4,5,6]])
print(np.zeros_like(a))
print(np.ones_like(a))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
# 获取数组a的shape:a.shape
# 获取数组a的元素类型：a.dtype
# 获取数组a的维度：a.ndim

print(zerosArr.shape)
print(zerosArr.dtype)
print(zerosArr.ndim)
print('----')
print(np.zeros_like(a).dtype)

(3, 3)
float64
2
----
int32


In [50]:
# 5. 数组的改值，获取值，切片，
# 5.1 一维数组的操作和list操作一样
a = np.array([2,32,44,24,1,35,23,11])

# 改值：
a[5] = 0
print(a)

# 截取[3, 5)号元素：
print(a[3:5])
# 截取[2, 最后]号元素：
print(a[2:])
# 翻转操作, 步长为1，负数从后往前：
print(a[::-1])
# 翻转操作，步长为2，负数从后往前，即隔一个数拿一个：
print(a[::-2])

[ 2 32 44 24  1  0 23 11]
[24  1]
[44 24  1  0 23 11]
[11 23  0  1 24 44 32  2]
[11  0 24 32]


In [75]:
# 5.2 二维数组的操作：
a = np.arange(0,25,1).reshape(5,5) # .arange(25) == .arange(0,25,1)
print(a)
# [第几横行, 开始元素:结束元素(不含)]
print(a[0,0:])
print(a[1,0:])
print('----')
# [开始元素:结束元素(不含), 第几竖行]
print(a[0:,2])
print(a[0:,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]
[5 6 7 8 9]
----
[ 2  7 12 17 22]
[ 3  8 13 18 23]


In [95]:
# 5.3 三维数组的操作，在深度学习特征数据处理时用的是最多的。
# 下面这个为3行5列3通道的数组
a = np.ones(45).reshape(3,5,3)
print(a)
print('----------------')

# [块，行，个]
# 这里即[第一块, 第一行, 第一个元素]改为8
a[1, 1, 1]=8
print(a)
# 
print('----------------')

# [[1:最后]块, [1:3)行, 第2个]改为99.99
a[1:, 1:3, 2] = 99.99
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
----------------
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 8. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
----------------
[[[ 1.    1.    1.  ]
  [ 1.    1.    1.  ]
  [ 1.    1.    1.  ]
  [ 1.    1.    1.  ]
  [ 1.    1.    1.  ]]

 [[ 1.    1.    1.  ]
  [ 1.    8.   99.99]
  [ 1.    1.   99.99]
  [ 1.    1.    1.  ]
  [ 1.    1.    1.  ]]

 [[ 1.    1.    1.  ]
  [ 1.    1.   99.99]
  [ 1.    1.   99.99]
  [ 1.    1.    1.  ]
  [ 1.    1.    1.  ]]]


In [110]:
# 6. 维度变换 .reshape()
a = np.arange(10)
b = a.reshape(2,5)
b1 = a.reshape(2,5)
print(a)
print('----')
print(b)
print(b1)

[0 1 2 3 4 5 6 7 8 9]
----
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [111]:
# 7. 维度交换 .swapaxes()
b.swapaxes(0,1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [119]:
a = np.arange(24).reshape(2,3,4)
# 三维数组的第0轴和第1轴进行了交换, 即上面的2, 3进行交换
b = a.swapaxes(0,1)
print(a)
print('-------')
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
-------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [8]:
# 将多维数组拆成一维数组：
a = np.arange(10).reshape(2,5)
b = a.flatten()
c = a.reshape(-1)
d = a.ravel()
print(a)
print(b)
print(c)
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
# 8. 数组堆叠 .hstack() .stack()
a = np.array([1,2,3,4])
b = np.array([3,4,5,6,])

print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 3 4 5 6]
[[1 2 3 4]
 [3 4 5 6]]
