In [1]:
# 1. numpy创建数组

import numpy as np
# 1.1 采用列表方式创建
a0 = np.array([1,2,3,4])
# 1.2 采用元组方式创建
a1 = np.array((1,2,3,4))

print(a0, a1)

[1 2 3 4] [1 2 3 4]


In [4]:
# 2. 创建多维数组
a = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]
